### ISSUE TITLE
[Bug] New lines aren't properly prefixed

### ISSUE THREAD

**Issue by AWRyder** [Protected/rowboat#1]
When a user sends a message on discord that contains a new line, the result on IRC is two different lines, the first one prefixed but the following ones are not.

Example: 
Awkens Ryder - Today at 9:15 PM
1234567890
1234567890
--- Results in ---
21:15:34    Rowboat  [#discworld] Awkens Ryder: 1234567890
21:15:35    Rowboat  1234567890

**Comment by Protected** [comment]
Not a bug, but I changed it because I don't care either way!
