### ISSUE TITLE
Kills channel is not configurable

### ISSUE THREAD

**Issue by mkumpan** [Protected/rowboat#3]
Changing the discord channel name to anything from "kills" kills the bot's ability to report kills.
ModEveRoles.js:339
`this.mainEnv.server.channels.find('name', 'kills').send(msg, {`

**Comment by AWRyder** [comment]
Should be fixed on [adbb7e6a](https://github.com/Protected/rowboat/commit/adbb7e6ad981b103dfe409a116e491382f5dfbce)
